name: Notify Slack about Dependabot PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  notify:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack about Dependabot PR
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "🤖 *Dependabot opened a new PR!*",
            "attachments": [
              {
                "color": "#439FE0",
                "fields": [
                  { "title": "Title", "value": "${{ github.event.pull_request.title }}", "short": false },
                  { "title": "Branch", "value": "${{ github.event.pull_request.head.ref }}", "short": true },
                  { "title": "Link", "value": "<${{ github.event.pull_request.html_url }}|Open PR>", "short": true }
                ]
              }
            ]
          }' \
          "$SLACK_WEBHOOK_URL" 
